sudo: required
dist: xenial
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.9.1
        - DOCKER_REPO=tiepie/raspbian-debootstrap
        - DATE=$(date +'%Y%m%d')
    matrix:
        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=stretch TIEPIE_ARCH=armv6l

        - ARCH=armhf INCLUDE=wget QEMU_ARCH=arm SUITE=buster  TIEPIE_ARCH=armv6l

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install --only-upgrade dpkg
    - echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get -yt bionic install qemu-user-static debootstrap
script:
    - travis_wait 60 sudo ./update.sh -t "$DATE" -a "$ARCH" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -s "$SUITE" -i "$INCLUDE" -v "$TIEPIE_ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO:$ARCH-$SUITE && docker push $DOCKER_REPO:$ARCH-$SUITE-$DATE; fi
